"""
IN Piura - Catalogo de Centros Poblados por Bloque de Intervencion.

ARCHIVO GENERADO por `generar_centros_poblados.py`. Para actualizar la
demografia, reemplace el Excel de origen y vuelva a ejecutar ese script; para
agregar un bloque o un centro poblado nuevo, escribalo aqui (nombre y bloque)
y luego ejecute el script para que complete sus datos.

Fuentes:
  - CentrosPoblados-INEI-Bloques_v5.xlsx (hoja "Lista CPs INEI Bloques V5"):
    relacion de centros poblados y comunidades campesinas por bloque.
  - CentrosPoblados-INEI-Bloques_Adicionales.xlsx (hoja
    "centrospobladosineibloques_v5"): poblacion total y por sexo, poblacion
    vulnerable, viviendas particulares y coordenadas de cada centro poblado;
    hoja "Hoja2" para los bloques 83 a 87, que solo trae poblacion total.

Estructura de cada entrada:
    "<codigo de bloque>": {
        "centros_poblados": [...],        # nombres, en el orden de la fuente
        "comunidades_campesinas": [...],
        "poblacion_total": int,           # suma de los CCPP del bloque
        "hombres": int, "mujeres": int,
        "poblacion_vulnerable": int, "viviendas": int,
        "demografia": [ {datos por centro poblado} ],
    }

Un mismo centro poblado puede estar asociado a varios bloques: los totales son
"poblacion de los centros poblados asociados al bloque", no poblacion residente
dentro del poligono, y no deben sumarse entre bloques.

Un centro poblado con "inferido": True es aquel cuya fila venia vacia en su
bloque y cuyos datos se tomaron de otro bloque donde el mismo centro poblado
(mismo IDCCPP) si figura completo.
"""

CENTROS_POBLADOS_BLOQUE = {
    "1": {
        "centros_poblados": ["Mamayaco", "Gramadal"],
        "comunidades_campesinas": [],
        "poblacion_total": 238, "hombres": 120, "mujeres": 118,
        "poblacion_vulnerable": 42, "viviendas": 95,
        "demografia": [
            {"centro_poblado": "Mamayaco", "poblacion_total": 204, "hombres": 103, "mujeres": 101,
             "poblacion_vulnerable": 37, "viviendas": 75, "tipo": "Rural",
             "utm_este": 642644.85, "utm_norte": 9392535.8},
            {"centro_poblado": "Gramadal", "poblacion_total": 34, "hombres": 17, "mujeres": 17,
             "poblacion_vulnerable": 5, "viviendas": 20, "tipo": "Rural",
             "utm_este": 645003.97, "utm_norte": 9392159.9},
        ],
    },
    "2": {
        "centros_poblados": ["Balcones de Talandracas"],
        "comunidades_campesinas": [],
        "poblacion_total": 691, "hombres": 364, "mujeres": 327,
        "poblacion_vulnerable": 83, "viviendas": 188,
        "demografia": [
            {"centro_poblado": "Balcones de Talandracas", "poblacion_total": 691, "hombres": 364, "mujeres": 327,
             "poblacion_vulnerable": 83, "viviendas": 188, "tipo": "Rural",
             "utm_este": 602137.15, "utm_norte": 9437858.35},
        ],
    },
    "3": {
        "centros_poblados": ["Los Checches", "Huayabal", "El Mirador", "Rincon de Geraldo", "Huasipe de Geraldo"],
        "comunidades_campesinas": [],
        "poblacion_total": 495, "hombres": 254, "mujeres": 241,
        "poblacion_vulnerable": 78, "viviendas": 143,
        "demografia": [
            {"centro_poblado": "Los Checches", "poblacion_total": 191, "hombres": 96, "mujeres": 95,
             "poblacion_vulnerable": 32, "viviendas": 53, "tipo": "Rural",
             "utm_este": 607045.09, "utm_norte": 9459366.26},
            {"centro_poblado": "Huayabal", "poblacion_total": 47, "hombres": 25, "mujeres": 22,
             "poblacion_vulnerable": 4, "viviendas": 20, "tipo": "Rural",
             "utm_este": 605127.04, "utm_norte": 9458671.03},
            {"centro_poblado": "El Mirador", "poblacion_total": 25, "hombres": 16, "mujeres": 9,
             "poblacion_vulnerable": 3, "viviendas": 6, "tipo": "Rural",
             "utm_este": 605865.68, "utm_norte": 9459026.7},
            {"centro_poblado": "Rincon de Geraldo", "poblacion_total": 116, "hombres": 62, "mujeres": 54,
             "poblacion_vulnerable": 14, "viviendas": 29, "tipo": "Rural",
             "utm_este": 608960.9, "utm_norte": 9458875.94},
            {"centro_poblado": "Huasipe de Geraldo", "poblacion_total": 116, "hombres": 55, "mujeres": 61,
             "poblacion_vulnerable": 25, "viviendas": 35, "tipo": "Rural",
             "utm_este": 608730.61, "utm_norte": 9459375.43},
        ],
    },
    "4": {
        "centros_poblados": ["San Antonio de Succhirca", "La Rinconada"],
        "comunidades_campesinas": [],
        "poblacion_total": 385, "hombres": 196, "mujeres": 189,
        "poblacion_vulnerable": 77, "viviendas": 116,
        "demografia": [
            {"centro_poblado": "San Antonio de Succhirca", "poblacion_total": 86, "hombres": 44, "mujeres": 42,
             "poblacion_vulnerable": 19, "viviendas": 35, "tipo": "Rural",
             "utm_este": 657458.69, "utm_norte": 9382940.69},
            {"centro_poblado": "La Rinconada", "poblacion_total": 299, "hombres": 152, "mujeres": 147,
             "poblacion_vulnerable": 58, "viviendas": 81, "tipo": "Rural",
             "utm_este": 655149.78, "utm_norte": 9384195.7},
        ],
    },
    "5": {
        "centros_poblados": ["Juan Velasco", "El Ala", "Linderos del Ala"],
        "comunidades_campesinas": [],
        "poblacion_total": 186, "hombres": 96, "mujeres": 90,
        "poblacion_vulnerable": 44, "viviendas": 73,
        "demografia": [
            {"centro_poblado": "Juan Velasco", "poblacion_total": 64, "hombres": 32, "mujeres": 32,
             "poblacion_vulnerable": 15, "viviendas": 25, "tipo": "Rural",
             "utm_este": 618461.1, "utm_norte": 9411761.41},
            {"centro_poblado": "El Ala", "poblacion_total": 69, "hombres": 33, "mujeres": 36,
             "poblacion_vulnerable": 22, "viviendas": 24, "tipo": "Rural",
             "utm_este": 618703.91, "utm_norte": 9413220.19},
            {"centro_poblado": "Linderos del Ala", "poblacion_total": 53, "hombres": 31, "mujeres": 22,
             "poblacion_vulnerable": 7, "viviendas": 24, "tipo": "Rural",
             "utm_este": 617460.89, "utm_norte": 9414954.41},
        ],
    },
    "6": {
        "centros_poblados": ["Guabal", "Nogal", "Guanabano Alto"],
        "comunidades_campesinas": [],
        "poblacion_total": 537, "hombres": 257, "mujeres": 280,
        "poblacion_vulnerable": 75, "viviendas": 166,
        "demografia": [
            {"centro_poblado": "Guabal", "poblacion_total": 280, "hombres": 133, "mujeres": 147,
             "poblacion_vulnerable": 47, "viviendas": 88, "tipo": "Rural",
             "utm_este": 607202.67, "utm_norte": 9454584.57},
            {"centro_poblado": "Nogal", "poblacion_total": 9, "hombres": 4, "mujeres": 5,
             "poblacion_vulnerable": 0, "viviendas": 3, "tipo": "Rural",
             "utm_este": 605223.43, "utm_norte": 9454965.51},
            {"centro_poblado": "Guanabano Alto", "poblacion_total": 248, "hombres": 120, "mujeres": 128,
             "poblacion_vulnerable": 28, "viviendas": 75, "tipo": "Rural",
             "utm_este": 604359.22, "utm_norte": 9454523.05},
        ],
    },
    "8": {
        "centros_poblados": ["Pirga"],
        "comunidades_campesinas": [],
        "poblacion_total": 322, "hombres": 163, "mujeres": 159,
        "poblacion_vulnerable": 39, "viviendas": 85,
        "demografia": [
            {"centro_poblado": "Pirga", "poblacion_total": 322, "hombres": 163, "mujeres": 159,
             "poblacion_vulnerable": 39, "viviendas": 85, "tipo": "Rural",
             "utm_este": 652350.86, "utm_norte": 9372850.14},
        ],
    },
    "9": {
        "centros_poblados": ["La Capilla", "El Higueron"],
        "comunidades_campesinas": [],
        "poblacion_total": 248, "hombres": 126, "mujeres": 122,
        "poblacion_vulnerable": 76, "viviendas": 93,
        "demografia": [
            {"centro_poblado": "La Capilla", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 654883.09, "utm_norte": 9398181.53},
            {"centro_poblado": "El Higueron", "poblacion_total": 248, "hombres": 126, "mujeres": 122,
             "poblacion_vulnerable": 76, "viviendas": 93, "tipo": "Rural",
             "utm_este": 654804.19, "utm_norte": 9396670.86},
        ],
    },
    "10": {
        "centros_poblados": ["La Peña"],
        "comunidades_campesinas": [],
        "poblacion_total": 146, "hombres": 83, "mujeres": 63,
        "poblacion_vulnerable": 19, "viviendas": 35,
        "demografia": [
            {"centro_poblado": "La Peña", "poblacion_total": 146, "hombres": 83, "mujeres": 63,
             "poblacion_vulnerable": 19, "viviendas": 35, "tipo": "Rural",
             "utm_este": 651029.35, "utm_norte": 9382625.27},
        ],
    },
    "11": {
        "centros_poblados": ["Taylin de Tuñali"],
        "comunidades_campesinas": [],
        "poblacion_total": 53, "hombres": 30, "mujeres": 23,
        "poblacion_vulnerable": 20, "viviendas": 34,
        "demografia": [
            {"centro_poblado": "Taylin de Tuñali", "poblacion_total": 53, "hombres": 30, "mujeres": 23,
             "poblacion_vulnerable": 20, "viviendas": 34, "tipo": "Rural",
             "utm_este": 621241.75, "utm_norte": 9440655.67},
        ],
    },
    "12": {
        "centros_poblados": ["Chacayo", "Santo Domingo"],
        "comunidades_campesinas": [],
        "poblacion_total": 105, "hombres": 55, "mujeres": 50,
        "poblacion_vulnerable": 43, "viviendas": 85,
        "demografia": [
            {"centro_poblado": "Chacayo", "poblacion_total": 105, "hombres": 55, "mujeres": 50,
             "poblacion_vulnerable": 43, "viviendas": 85, "tipo": "Rural",
             "utm_este": 625612.13, "utm_norte": 9443771.51},
            {"centro_poblado": "Santo Domingo", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 624624.72, "utm_norte": 9443986.85},
        ],
    },
    "13": {
        "centros_poblados": ["Huacas"],
        "comunidades_campesinas": [],
        "poblacion_total": 139, "hombres": 74, "mujeres": 65,
        "poblacion_vulnerable": 41, "viviendas": 49,
        "demografia": [
            {"centro_poblado": "Huacas", "poblacion_total": 139, "hombres": 74, "mujeres": 65,
             "poblacion_vulnerable": 41, "viviendas": 49, "tipo": "Rural",
             "utm_este": 619534.5, "utm_norte": 9442810.91},
        ],
    },
    "14": {
        "centros_poblados": ["La Laja", "Overazal"],
        "comunidades_campesinas": [],
        "poblacion_total": 38, "hombres": 18, "mujeres": 20,
        "poblacion_vulnerable": 12, "viviendas": 20,
        "demografia": [
            {"centro_poblado": "La Laja", "poblacion_total": 22, "hombres": 11, "mujeres": 11,
             "poblacion_vulnerable": 8, "viviendas": 12, "tipo": "Rural",
             "utm_este": 624674.36, "utm_norte": 9437695.83},
            {"centro_poblado": "Overazal", "poblacion_total": 16, "hombres": 7, "mujeres": 9,
             "poblacion_vulnerable": 4, "viviendas": 8, "tipo": "Rural",
             "utm_este": 624064.49, "utm_norte": 9437299.42},
        ],
    },
    "15": {
        "centros_poblados": ["Jacanacas"],
        "comunidades_campesinas": [],
        "poblacion_total": 130, "hombres": 57, "mujeres": 73,
        "poblacion_vulnerable": 49, "viviendas": 64,
        "demografia": [
            {"centro_poblado": "Jacanacas", "poblacion_total": 130, "hombres": 57, "mujeres": 73,
             "poblacion_vulnerable": 49, "viviendas": 64, "tipo": "Rural",
             "utm_este": 619642.9, "utm_norte": 9437545.2},
        ],
    },
    "16": {
        "centros_poblados": ["Laguna de Paltama"],
        "comunidades_campesinas": [],
        "poblacion_total": 153, "hombres": 72, "mujeres": 81,
        "poblacion_vulnerable": 46, "viviendas": 47,
        "demografia": [
            {"centro_poblado": "Laguna de Paltama", "poblacion_total": 153, "hombres": 72, "mujeres": 81,
             "poblacion_vulnerable": 46, "viviendas": 47, "tipo": "Rural",
             "utm_este": 652386.41, "utm_norte": 9381114.27},
        ],
    },
    "17": {
        "centros_poblados": ["El Checo"],
        "comunidades_campesinas": [],
        "poblacion_total": 91, "hombres": 46, "mujeres": 45,
        "poblacion_vulnerable": 20, "viviendas": 31,
        "demografia": [
            {"centro_poblado": "El Checo", "poblacion_total": 91, "hombres": 46, "mujeres": 45,
             "poblacion_vulnerable": 20, "viviendas": 31, "tipo": "Rural",
             "utm_este": 618239.16, "utm_norte": 9437385.38},
        ],
    },
    "18": {
        "centros_poblados": ["Piedra Blanca"],
        "comunidades_campesinas": [],
        "poblacion_total": 28, "hombres": 13, "mujeres": 15,
        "poblacion_vulnerable": 7, "viviendas": 13,
        "demografia": [
            {"centro_poblado": "Piedra Blanca", "poblacion_total": 28, "hombres": 13, "mujeres": 15,
             "poblacion_vulnerable": 7, "viviendas": 13, "tipo": "Rural",
             "utm_este": 657269.31, "utm_norte": 9392382.73},
        ],
    },
    "19": {
        "centros_poblados": ["Tabluran", "Nuevo Progreso"],
        "comunidades_campesinas": [],
        "poblacion_total": 132, "hombres": 68, "mujeres": 64,
        "poblacion_vulnerable": 16, "viviendas": 37,
        "demografia": [
            {"centro_poblado": "Tabluran", "poblacion_total": 83, "hombres": 43, "mujeres": 40,
             "poblacion_vulnerable": 7, "viviendas": 20, "tipo": "Rural",
             "utm_este": 665247.51, "utm_norte": 9390026.99},
            {"centro_poblado": "Nuevo Progreso", "poblacion_total": 49, "hombres": 25, "mujeres": 24,
             "poblacion_vulnerable": 9, "viviendas": 17, "tipo": "Rural",
             "utm_este": 665109.12, "utm_norte": 9390808.75},
        ],
    },
    "20": {
        "centros_poblados": ["Tupac Amaru"],
        "comunidades_campesinas": [],
        "poblacion_total": 149, "hombres": 57, "mujeres": 92,
        "poblacion_vulnerable": 26, "viviendas": 38,
        "demografia": [
            {"centro_poblado": "Tupac Amaru", "poblacion_total": 149, "hombres": 57, "mujeres": 92,
             "poblacion_vulnerable": 26, "viviendas": 38, "tipo": "Rural",
             "utm_este": 649656.14, "utm_norte": 9376987.26},
        ],
    },
    "21": {
        "centros_poblados": ["Huamala Alto"],
        "comunidades_campesinas": [],
        "poblacion_total": 47, "hombres": 26, "mujeres": 21,
        "poblacion_vulnerable": 6, "viviendas": 18,
        "demografia": [
            {"centro_poblado": "Huamala Alto", "poblacion_total": 47, "hombres": 26, "mujeres": 21,
             "poblacion_vulnerable": 6, "viviendas": 18, "tipo": "Rural",
             "utm_este": 654278.27, "utm_norte": 9418170.89},
        ],
    },
    "22": {
        "centros_poblados": ["Platanal Bajo"],
        "comunidades_campesinas": [],
        "poblacion_total": 197, "hombres": 101, "mujeres": 96,
        "poblacion_vulnerable": 43, "viviendas": 79,
        "demografia": [
            {"centro_poblado": "Platanal Bajo", "poblacion_total": 197, "hombres": 101, "mujeres": 96,
             "poblacion_vulnerable": 43, "viviendas": 79, "tipo": "Rural",
             "utm_este": 601363.12, "utm_norte": 9442900.09},
        ],
    },
    "23": {
        "centros_poblados": ["Jacanacas", "Nueva Esperanza"],
        "comunidades_campesinas": [],
        "poblacion_total": 161, "hombres": 72, "mujeres": 89,
        "poblacion_vulnerable": 54, "viviendas": 77,
        "demografia": [
            {"centro_poblado": "Jacanacas", "poblacion_total": 130, "hombres": 57, "mujeres": 73,
             "poblacion_vulnerable": 49, "viviendas": 64, "tipo": "Rural",
             "utm_este": 619642.9, "utm_norte": 9437545.2},
            {"centro_poblado": "Nueva Esperanza", "poblacion_total": 31, "hombres": 15, "mujeres": 16,
             "poblacion_vulnerable": 5, "viviendas": 13, "tipo": "Rural",
             "utm_este": 619888.69, "utm_norte": 9439237.63},
        ],
    },
    "24": {
        "centros_poblados": ["Coyona"],
        "comunidades_campesinas": [],
        "poblacion_total": 443, "hombres": 226, "mujeres": 217,
        "poblacion_vulnerable": 77, "viviendas": 154,
        "demografia": [
            {"centro_poblado": "Coyona", "poblacion_total": 443, "hombres": 226, "mujeres": 217,
             "poblacion_vulnerable": 77, "viviendas": 154, "tipo": "Rural",
             "utm_este": 652905.44, "utm_norte": 9413563.83},
        ],
    },
    "25": {
        "centros_poblados": ["Cruz Pampa-yapatera"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Cruz Pampa-yapatera", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 595824.6, "utm_norte": 9440901.51},
        ],
    },
    "26": {
        "centros_poblados": ["La Laguna"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "La Laguna", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 650045.05, "utm_norte": 9425329.88},
        ],
    },
    "27": {
        "centros_poblados": ["Nueva Esperanza de Misquis", "Linderos de Misquis"],
        "comunidades_campesinas": [],
        "poblacion_total": 111, "hombres": 54, "mujeres": 57,
        "poblacion_vulnerable": 23, "viviendas": 39,
        "demografia": [
            {"centro_poblado": "Nueva Esperanza de Misquis", "poblacion_total": 83, "hombres": 41, "mujeres": 42,
             "poblacion_vulnerable": 16, "viviendas": 25, "tipo": "Rural",
             "utm_este": 612288.24, "utm_norte": 9449603.11},
            {"centro_poblado": "Linderos de Misquis", "poblacion_total": 28, "hombres": 13, "mujeres": 15,
             "poblacion_vulnerable": 7, "viviendas": 14, "tipo": "Rural",
             "utm_este": 612421.49, "utm_norte": 9450333.31},
        ],
    },
    "28": {
        "centros_poblados": ["Abalque"],
        "comunidades_campesinas": [],
        "poblacion_total": 66, "hombres": 37, "mujeres": 29,
        "poblacion_vulnerable": 10, "viviendas": 24,
        "demografia": [
            {"centro_poblado": "Abalque", "poblacion_total": 66, "hombres": 37, "mujeres": 29,
             "poblacion_vulnerable": 10, "viviendas": 24, "tipo": "Rural",
             "utm_este": 653990.93, "utm_norte": 9423222.83},
        ],
    },
    "29": {
        "centros_poblados": ["Santa Cruz"],
        "comunidades_campesinas": [],
        "poblacion_total": 271, "hombres": 117, "mujeres": 154,
        "poblacion_vulnerable": 30, "viviendas": 62,
        "demografia": [
            {"centro_poblado": "Santa Cruz", "poblacion_total": 271, "hombres": 117, "mujeres": 154,
             "poblacion_vulnerable": 30, "viviendas": 62, "tipo": "Rural",
             "utm_este": 660094.1, "utm_norte": 9397025.12},
        ],
    },
    "30": {
        "centros_poblados": ["Chamelico", "Sapce"],
        "comunidades_campesinas": [],
        "poblacion_total": 168, "hombres": 93, "mujeres": 75,
        "poblacion_vulnerable": 46, "viviendas": 85,
        "demografia": [
            {"centro_poblado": "Chamelico", "poblacion_total": 75, "hombres": 40, "mujeres": 35,
             "poblacion_vulnerable": 16, "viviendas": 35, "tipo": "Rural",
             "utm_este": 651541.35, "utm_norte": 9424082.35},
            {"centro_poblado": "Sapce", "poblacion_total": 93, "hombres": 53, "mujeres": 40,
             "poblacion_vulnerable": 30, "viviendas": 50, "tipo": "Rural",
             "utm_este": 651375.17, "utm_norte": 9424124.17},
        ],
    },
    "32": {
        "centros_poblados": ["Panecillo"],
        "comunidades_campesinas": [],
        "poblacion_total": 230, "hombres": 124, "mujeres": 106,
        "poblacion_vulnerable": 53, "viviendas": 99,
        "demografia": [
            {"centro_poblado": "Panecillo", "poblacion_total": 230, "hombres": 124, "mujeres": 106,
             "poblacion_vulnerable": 53, "viviendas": 99, "tipo": "Rural",
             "utm_este": 599625.26, "utm_norte": 9441489.74},
        ],
    },
    "33": {
        "centros_poblados": ["Sambe"],
        "comunidades_campesinas": [],
        "poblacion_total": 63, "hombres": 35, "mujeres": 28,
        "poblacion_vulnerable": 14, "viviendas": 24,
        "demografia": [
            {"centro_poblado": "Sambe", "poblacion_total": 63, "hombres": 35, "mujeres": 28,
             "poblacion_vulnerable": 14, "viviendas": 24, "tipo": "Rural",
             "utm_este": 646947.61, "utm_norte": 9430998.28},
        ],
    },
    "34": {
        "centros_poblados": ["Maray Grande", "Maray Chico"],
        "comunidades_campesinas": [],
        "poblacion_total": 142, "hombres": 70, "mujeres": 72,
        "poblacion_vulnerable": 31, "viviendas": 59,
        "demografia": [
            {"centro_poblado": "Maray Grande", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 645933.18, "utm_norte": 9426502.77},
            {"centro_poblado": "Maray Chico", "poblacion_total": 142, "hombres": 70, "mujeres": 72,
             "poblacion_vulnerable": 31, "viviendas": 59, "tipo": "Rural",
             "utm_este": 645458.93, "utm_norte": 9426236.79},
        ],
    },
    "35": {
        "centros_poblados": ["Chamelico", "Quitahuajara"],
        "comunidades_campesinas": [],
        "poblacion_total": 198, "hombres": 98, "mujeres": 100,
        "poblacion_vulnerable": 51, "viviendas": 73,
        "demografia": [
            {"centro_poblado": "Chamelico", "poblacion_total": 127, "hombres": 62, "mujeres": 65,
             "poblacion_vulnerable": 27, "viviendas": 43, "tipo": "Rural",
             "utm_este": 654871.49, "utm_norte": 9395515.21},
            {"centro_poblado": "Quitahuajara", "poblacion_total": 71, "hombres": 36, "mujeres": 35,
             "poblacion_vulnerable": 24, "viviendas": 30, "tipo": "Rural",
             "utm_este": 653653.36, "utm_norte": 9395027.27},
        ],
    },
    "36": {
        "centros_poblados": ["Guabal"],
        "comunidades_campesinas": [],
        "poblacion_total": 280, "hombres": 133, "mujeres": 147,
        "poblacion_vulnerable": 47, "viviendas": 88,
        "demografia": [
            {"centro_poblado": "Guabal", "poblacion_total": 280, "hombres": 133, "mujeres": 147,
             "poblacion_vulnerable": 47, "viviendas": 88, "tipo": "Rural",
             "utm_este": 607202.67, "utm_norte": 9454584.57},
        ],
    },
    "37": {
        "centros_poblados": ["El Papayo"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "El Papayo", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 649585.55, "utm_norte": 9424524.15},
        ],
    },
    "38": {
        "centros_poblados": ["Ullma"],
        "comunidades_campesinas": [],
        "poblacion_total": 157, "hombres": 80, "mujeres": 77,
        "poblacion_vulnerable": 29, "viviendas": 70,
        "demografia": [
            {"centro_poblado": "Ullma", "poblacion_total": 157, "hombres": 80, "mujeres": 77,
             "poblacion_vulnerable": 29, "viviendas": 70, "tipo": "Rural",
             "utm_este": 646975.89, "utm_norte": 9428518.72},
        ],
    },
    "39": {
        "centros_poblados": ["La Cria"],
        "comunidades_campesinas": [],
        "poblacion_total": 327, "hombres": 166, "mujeres": 161,
        "poblacion_vulnerable": 35, "viviendas": 85,
        "demografia": [
            {"centro_poblado": "La Cria", "poblacion_total": 327, "hombres": 166, "mujeres": 161,
             "poblacion_vulnerable": 35, "viviendas": 85, "tipo": "Rural",
             "utm_este": 619276.57, "utm_norte": 9449240.85},
        ],
    },
    "40": {
        "centros_poblados": ["Chorro Blanco", "Chacchacal"],
        "comunidades_campesinas": [],
        "poblacion_total": 58, "hombres": 38, "mujeres": 20,
        "poblacion_vulnerable": 14, "viviendas": 44,
        "demografia": [
            {"centro_poblado": "Chorro Blanco", "poblacion_total": 25, "hombres": 15, "mujeres": 10,
             "poblacion_vulnerable": 6, "viviendas": 20, "tipo": "Rural",
             "utm_este": 654090.38, "utm_norte": 9424088.39},
            {"centro_poblado": "Chacchacal", "poblacion_total": 33, "hombres": 23, "mujeres": 10,
             "poblacion_vulnerable": 8, "viviendas": 24, "tipo": "Rural",
             "utm_este": 653864.09, "utm_norte": 9424187.48},
        ],
    },
    "41": {
        "centros_poblados": ["Cambruran"],
        "comunidades_campesinas": [],
        "poblacion_total": 54, "hombres": 27, "mujeres": 27,
        "poblacion_vulnerable": 15, "viviendas": 15,
        "demografia": [
            {"centro_poblado": "Cambruran", "poblacion_total": 54, "hombres": 27, "mujeres": 27,
             "poblacion_vulnerable": 15, "viviendas": 15, "tipo": "Rural",
             "utm_este": 660839.13, "utm_norte": 9394198.85},
        ],
    },
    "42": {
        "centros_poblados": ["Santa Rosa de Chirimoyos"],
        "comunidades_campesinas": [],
        "poblacion_total": 131, "hombres": 63, "mujeres": 68,
        "poblacion_vulnerable": 29, "viviendas": 53,
        "demografia": [
            {"centro_poblado": "Santa Rosa de Chirimoyos", "poblacion_total": 131, "hombres": 63, "mujeres": 68,
             "poblacion_vulnerable": 29, "viviendas": 53, "tipo": "Rural",
             "utm_este": 625716.5, "utm_norte": 9434887.24},
        ],
    },
    "43": {
        "centros_poblados": ["Pizarrume", "Coyona"],
        "comunidades_campesinas": [],
        "poblacion_total": 296, "hombres": 131, "mujeres": 165,
        "poblacion_vulnerable": 42, "viviendas": 99,
        "demografia": [
            {"centro_poblado": "Pizarrume", "poblacion_total": 222, "hombres": 100, "mujeres": 122,
             "poblacion_vulnerable": 31, "viviendas": 65, "tipo": "Rural",
             "utm_este": 656144.81, "utm_norte": 9395740.94},
            {"centro_poblado": "Coyona", "poblacion_total": 74, "hombres": 31, "mujeres": 43,
             "poblacion_vulnerable": 11, "viviendas": 34, "tipo": "Rural",
             "utm_este": 657110.11, "utm_norte": 9395344.29},
        ],
    },
    "44": {
        "centros_poblados": ["Cruz de Piedra"],
        "comunidades_campesinas": [],
        "poblacion_total": 74, "hombres": 39, "mujeres": 35,
        "poblacion_vulnerable": 10, "viviendas": 25,
        "demografia": [
            {"centro_poblado": "Cruz de Piedra", "poblacion_total": 74, "hombres": 39, "mujeres": 35,
             "poblacion_vulnerable": 10, "viviendas": 25, "tipo": "Rural",
             "utm_este": 662961.66, "utm_norte": 9401792.7},
        ],
    },
    "46": {
        "centros_poblados": ["Nangay"],
        "comunidades_campesinas": [],
        "poblacion_total": 149, "hombres": 85, "mujeres": 64,
        "poblacion_vulnerable": 23, "viviendas": 55,
        "demografia": [
            {"centro_poblado": "Nangay", "poblacion_total": 149, "hombres": 85, "mujeres": 64,
             "poblacion_vulnerable": 23, "viviendas": 55, "tipo": "Rural",
             "utm_este": 638677.56, "utm_norte": 9431997.53},
        ],
    },
    "47": {
        "centros_poblados": ["Gaspar"],
        "comunidades_campesinas": [],
        "poblacion_total": 132, "hombres": 55, "mujeres": 77,
        "poblacion_vulnerable": 19, "viviendas": 41,
        "demografia": [
            {"centro_poblado": "Gaspar", "poblacion_total": 132, "hombres": 55, "mujeres": 77,
             "poblacion_vulnerable": 19, "viviendas": 41, "tipo": "Rural",
             "utm_este": 659798.42, "utm_norte": 9401280.95},
        ],
    },
    "49": {
        "centros_poblados": ["Las Huacas"],
        "comunidades_campesinas": [],
        "poblacion_total": 84, "hombres": 43, "mujeres": 41,
        "poblacion_vulnerable": 15, "viviendas": 27,
        "demografia": [
            {"centro_poblado": "Las Huacas", "poblacion_total": 84, "hombres": 43, "mujeres": 41,
             "poblacion_vulnerable": 15, "viviendas": 27, "tipo": "Rural",
             "utm_este": 643033.0, "utm_norte": 9438448.94},
        ],
    },
    "51": {
        "centros_poblados": ["Shain", "Talla"],
        "comunidades_campesinas": [],
        "poblacion_total": 348, "hombres": 181, "mujeres": 167,
        "poblacion_vulnerable": 61, "viviendas": 98,
        "demografia": [
            {"centro_poblado": "Shain", "poblacion_total": 207, "hombres": 109, "mujeres": 98,
             "poblacion_vulnerable": 37, "viviendas": 57, "tipo": "Rural",
             "utm_este": 655081.83, "utm_norte": 9378773.32},
            {"centro_poblado": "Talla", "poblacion_total": 141, "hombres": 72, "mujeres": 69,
             "poblacion_vulnerable": 24, "viviendas": 41, "tipo": "Rural",
             "utm_este": 655980.56, "utm_norte": 9378369.6},
        ],
    },
    "52": {
        "centros_poblados": ["Miraflores"],
        "comunidades_campesinas": [],
        "poblacion_total": 43, "hombres": 21, "mujeres": 22,
        "poblacion_vulnerable": 7, "viviendas": 13,
        "demografia": [
            {"centro_poblado": "Miraflores", "poblacion_total": 43, "hombres": 21, "mujeres": 22,
             "poblacion_vulnerable": 7, "viviendas": 13, "tipo": "Rural",
             "utm_este": 640794.17, "utm_norte": 9437778.18},
        ],
    },
    "53": {
        "centros_poblados": ["Zururan"],
        "comunidades_campesinas": [],
        "poblacion_total": 140, "hombres": 66, "mujeres": 74,
        "poblacion_vulnerable": 19, "viviendas": 44,
        "demografia": [
            {"centro_poblado": "Zururan", "poblacion_total": 140, "hombres": 66, "mujeres": 74,
             "poblacion_vulnerable": 19, "viviendas": 44, "tipo": "Rural",
             "utm_este": 666185.22, "utm_norte": 9395689.38},
        ],
    },
    "55": {
        "centros_poblados": ["Las Huacas"],
        "comunidades_campesinas": [],
        "poblacion_total": 84, "hombres": 43, "mujeres": 41,
        "poblacion_vulnerable": 15, "viviendas": 27,
        "demografia": [
            {"centro_poblado": "Las Huacas", "poblacion_total": 84, "hombres": 43, "mujeres": 41,
             "poblacion_vulnerable": 15, "viviendas": 27, "tipo": "Rural",
             "utm_este": 643033.0, "utm_norte": 9438448.94},
        ],
    },
    "56": {
        "centros_poblados": ["Banda de la Cruz", "Putagas"],
        "comunidades_campesinas": [],
        "poblacion_total": 375, "hombres": 181, "mujeres": 194,
        "poblacion_vulnerable": 41, "viviendas": 74,
        "demografia": [
            {"centro_poblado": "Banda de la Cruz", "poblacion_total": 75, "hombres": 35, "mujeres": 40,
             "poblacion_vulnerable": 13, "viviendas": 19, "tipo": "Rural",
             "utm_este": 619831.93, "utm_norte": 9452099.16},
            {"centro_poblado": "Putagas", "poblacion_total": 300, "hombres": 146, "mujeres": 154,
             "poblacion_vulnerable": 28, "viviendas": 55, "tipo": "Rural",
             "utm_este": 620357.28, "utm_norte": 9451508.47},
        ],
    },
    "57": {
        "centros_poblados": ["San Lorenzo", "Taspa"],
        "comunidades_campesinas": [],
        "poblacion_total": 376, "hombres": 183, "mujeres": 193,
        "poblacion_vulnerable": 77, "viviendas": 126,
        "demografia": [
            {"centro_poblado": "San Lorenzo", "poblacion_total": 126, "hombres": 65, "mujeres": 61,
             "poblacion_vulnerable": 24, "viviendas": 38, "tipo": "Rural",
             "utm_este": 633192.57, "utm_norte": 9439427.03},
            {"centro_poblado": "Taspa", "poblacion_total": 250, "hombres": 118, "mujeres": 132,
             "poblacion_vulnerable": 53, "viviendas": 88, "tipo": "Rural",
             "utm_este": 631620.67, "utm_norte": 9440841.25},
        ],
    },
    "58": {
        "centros_poblados": ["Linderos de Maray", "Maray"],
        "comunidades_campesinas": [],
        "poblacion_total": 329, "hombres": 165, "mujeres": 164,
        "poblacion_vulnerable": 55, "viviendas": 138,
        "demografia": [
            {"centro_poblado": "Linderos de Maray", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 621488.19, "utm_norte": 9427193.77},
            {"centro_poblado": "Maray", "poblacion_total": 329, "hombres": 165, "mujeres": 164,
             "poblacion_vulnerable": 55, "viviendas": 138, "tipo": "Rural",
             "utm_este": 618786.21, "utm_norte": 9426010.78},
        ],
    },
    "59": {
        "centros_poblados": ["Guabo"],
        "comunidades_campesinas": [],
        "poblacion_total": 6, "hombres": 2, "mujeres": 4,
        "poblacion_vulnerable": 1, "viviendas": 2,
        "demografia": [
            {"centro_poblado": "Guabo", "poblacion_total": 6, "hombres": 2, "mujeres": 4,
             "poblacion_vulnerable": 1, "viviendas": 2, "tipo": "Rural",
             "utm_este": 630829.59, "utm_norte": 9441636.71},
        ],
    },
    "60": {
        "centros_poblados": ["Flor de Cafe"],
        "comunidades_campesinas": [],
        "poblacion_total": 111, "hombres": 63, "mujeres": 48,
        "poblacion_vulnerable": 19, "viviendas": 41,
        "demografia": [
            {"centro_poblado": "Flor de Cafe", "poblacion_total": 111, "hombres": 63, "mujeres": 48,
             "poblacion_vulnerable": 19, "viviendas": 41, "tipo": "Rural",
             "utm_este": 653316.31, "utm_norte": 9427146.29},
        ],
    },
    "61": {
        "centros_poblados": ["Pedregal"],
        "comunidades_campesinas": [],
        "poblacion_total": 14, "hombres": 6, "mujeres": 8,
        "poblacion_vulnerable": 4, "viviendas": 5,
        "demografia": [
            {"centro_poblado": "Pedregal", "poblacion_total": 14, "hombres": 6, "mujeres": 8,
             "poblacion_vulnerable": 4, "viviendas": 5, "tipo": "Rural",
             "utm_este": 646143.3, "utm_norte": 9424311.1},
        ],
    },
    "63": {
        "centros_poblados": ["Shuturumbe"],
        "comunidades_campesinas": [],
        "poblacion_total": 87, "hombres": 42, "mujeres": 45,
        "poblacion_vulnerable": 12, "viviendas": 27,
        "demografia": [
            {"centro_poblado": "Shuturumbe", "poblacion_total": 87, "hombres": 42, "mujeres": 45,
             "poblacion_vulnerable": 12, "viviendas": 27, "tipo": "Rural",
             "utm_este": 654547.82, "utm_norte": 9414055.34},
        ],
    },
    "64": {
        "centros_poblados": ["Pariamarca Centro"],
        "comunidades_campesinas": [],
        "poblacion_total": 311, "hombres": 152, "mujeres": 159,
        "poblacion_vulnerable": 51, "viviendas": 108,
        "demografia": [
            {"centro_poblado": "Pariamarca Centro", "poblacion_total": 311, "hombres": 152, "mujeres": 159,
             "poblacion_vulnerable": 51, "viviendas": 108, "tipo": "Rural",
             "utm_este": 656565.76, "utm_norte": 9428946.04},
        ],
    },
    "66": {
        "centros_poblados": ["Huamala Baja"],
        "comunidades_campesinas": [],
        "poblacion_total": 45, "hombres": 22, "mujeres": 23,
        "poblacion_vulnerable": 15, "viviendas": 29,
        "demografia": [
            {"centro_poblado": "Huamala Baja", "poblacion_total": 45, "hombres": 22, "mujeres": 23,
             "poblacion_vulnerable": 15, "viviendas": 29, "tipo": "Rural",
             "utm_este": 653063.72, "utm_norte": 9418044.95},
        ],
    },
    "67": {
        "centros_poblados": ["Piedra Grande"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 8,
        "demografia": [
            {"centro_poblado": "Piedra Grande", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 8, "tipo": "Rural",
             "utm_este": 654231.86, "utm_norte": 9393637.88},
        ],
    },
    "68": {
        "centros_poblados": ["Tabluran"],
        "comunidades_campesinas": [],
        "poblacion_total": 83, "hombres": 43, "mujeres": 40,
        "poblacion_vulnerable": 7, "viviendas": 20,
        "demografia": [
            {"centro_poblado": "Tabluran", "poblacion_total": 83, "hombres": 43, "mujeres": 40,
             "poblacion_vulnerable": 7, "viviendas": 20, "tipo": "Rural",
             "utm_este": 665247.51, "utm_norte": 9390026.99, "inferido": True},
        ],
    },
    "69": {
        "centros_poblados": ["Molle", "Hualanga Pampa"],
        "comunidades_campesinas": [],
        "poblacion_total": 133, "hombres": 69, "mujeres": 64,
        "poblacion_vulnerable": 26, "viviendas": 35,
        "demografia": [
            {"centro_poblado": "Molle", "poblacion_total": 100, "hombres": 52, "mujeres": 48,
             "poblacion_vulnerable": 17, "viviendas": 24, "tipo": "Rural",
             "utm_este": 662567.85, "utm_norte": 9391942.48},
            {"centro_poblado": "Hualanga Pampa", "poblacion_total": 33, "hombres": 17, "mujeres": 16,
             "poblacion_vulnerable": 9, "viviendas": 11, "tipo": "Rural",
             "utm_este": 661990.59, "utm_norte": 9392306.86},
        ],
    },
    "70": {
        "centros_poblados": ["Zururan"],
        "comunidades_campesinas": [],
        "poblacion_total": 140, "hombres": 66, "mujeres": 74,
        "poblacion_vulnerable": 19, "viviendas": 44,
        "demografia": [
            {"centro_poblado": "Zururan", "poblacion_total": 140, "hombres": 66, "mujeres": 74,
             "poblacion_vulnerable": 19, "viviendas": 44, "tipo": "Rural",
             "utm_este": 666185.22, "utm_norte": 9395689.38},
        ],
    },
    "71": {
        "centros_poblados": ["Pirga"],
        "comunidades_campesinas": [],
        "poblacion_total": 322, "hombres": 163, "mujeres": 159,
        "poblacion_vulnerable": 39, "viviendas": 85,
        "demografia": [
            {"centro_poblado": "Pirga", "poblacion_total": 322, "hombres": 163, "mujeres": 159,
             "poblacion_vulnerable": 39, "viviendas": 85, "tipo": "Rural",
             "utm_este": 652350.86, "utm_norte": 9372850.14},
        ],
    },
    "72": {
        "centros_poblados": ["Ramon Castilla"],
        "comunidades_campesinas": [],
        "poblacion_total": 216, "hombres": 108, "mujeres": 108,
        "poblacion_vulnerable": 49, "viviendas": 56,
        "demografia": [
            {"centro_poblado": "Ramon Castilla", "poblacion_total": 216, "hombres": 108, "mujeres": 108,
             "poblacion_vulnerable": 49, "viviendas": 56, "tipo": "Rural",
             "utm_este": 662207.2, "utm_norte": 9390946.97},
        ],
    },
    "73": {
        "centros_poblados": ["Chococa"],
        "comunidades_campesinas": [],
        "poblacion_total": 104, "hombres": 42, "mujeres": 62,
        "poblacion_vulnerable": 33, "viviendas": 34,
        "demografia": [
            {"centro_poblado": "Chococa", "poblacion_total": 104, "hombres": 42, "mujeres": 62,
             "poblacion_vulnerable": 33, "viviendas": 34, "tipo": "Rural",
             "utm_este": 658506.6, "utm_norte": 9394710.52},
        ],
    },
    "74": {
        "centros_poblados": ["Chalpa"],
        "comunidades_campesinas": [],
        "poblacion_total": 67, "hombres": 34, "mujeres": 33,
        "poblacion_vulnerable": 13, "viviendas": 43,
        "demografia": [
            {"centro_poblado": "Chalpa", "poblacion_total": 67, "hombres": 34, "mujeres": 33,
             "poblacion_vulnerable": 13, "viviendas": 43, "tipo": "Rural",
             "utm_este": 651934.91, "utm_norte": 9389520.12},
        ],
    },
    "75": {
        "centros_poblados": ["San Cristobal", "Sanchez Cerro"],
        "comunidades_campesinas": [],
        "poblacion_total": 625, "hombres": 296, "mujeres": 329,
        "poblacion_vulnerable": 113, "viviendas": 201,
        "demografia": [
            {"centro_poblado": "San Cristobal", "poblacion_total": 466, "hombres": 220, "mujeres": 246,
             "poblacion_vulnerable": 77, "viviendas": 159, "tipo": "Rural",
             "utm_este": 655751.1, "utm_norte": 9401225.57},
            {"centro_poblado": "Sanchez Cerro", "poblacion_total": 159, "hombres": 76, "mujeres": 83,
             "poblacion_vulnerable": 36, "viviendas": 42, "tipo": "Rural",
             "utm_este": 657048.94, "utm_norte": 9402493.79},
        ],
    },
    "76": {
        "centros_poblados": ["Sahuate Hualanga", "Hualanga"],
        "comunidades_campesinas": [],
        "poblacion_total": 388, "hombres": 196, "mujeres": 192,
        "poblacion_vulnerable": 57, "viviendas": 110,
        "demografia": [
            {"centro_poblado": "Sahuate Hualanga", "poblacion_total": 197, "hombres": 101, "mujeres": 96,
             "poblacion_vulnerable": 21, "viviendas": 54, "tipo": "Rural",
             "utm_este": 657728.52, "utm_norte": 9377721.08},
            {"centro_poblado": "Hualanga", "poblacion_total": 191, "hombres": 95, "mujeres": 96,
             "poblacion_vulnerable": 36, "viviendas": 56, "tipo": "Rural",
             "utm_este": 657466.93, "utm_norte": 9377587.27},
        ],
    },
    "77": {
        "centros_poblados": ["Miguel Pampa"],
        "comunidades_campesinas": [],
        "poblacion_total": 188, "hombres": 95, "mujeres": 93,
        "poblacion_vulnerable": 21, "viviendas": 74,
        "demografia": [
            {"centro_poblado": "Miguel Pampa", "poblacion_total": 188, "hombres": 95, "mujeres": 93,
             "poblacion_vulnerable": 21, "viviendas": 74, "tipo": "Rural",
             "utm_este": 639388.81, "utm_norte": 9410923.71},
        ],
    },
    "78": {
        "centros_poblados": ["Tasajeras"],
        "comunidades_campesinas": [],
        "poblacion_total": 114, "hombres": 59, "mujeres": 55,
        "poblacion_vulnerable": 28, "viviendas": 40,
        "demografia": [
            {"centro_poblado": "Tasajeras", "poblacion_total": 114, "hombres": 59, "mujeres": 55,
             "poblacion_vulnerable": 28, "viviendas": 40, "tipo": "Rural",
             "utm_este": 619017.55, "utm_norte": 9439715.03},
        ],
    },
    "79": {
        "centros_poblados": ["Huabal", "Almirante Miguel Grau"],
        "comunidades_campesinas": [],
        "poblacion_total": 219, "hombres": 105, "mujeres": 114,
        "poblacion_vulnerable": 47, "viviendas": 97,
        "demografia": [
            {"centro_poblado": "Huabal", "poblacion_total": 161, "hombres": 75, "mujeres": 86,
             "poblacion_vulnerable": 26, "viviendas": 65, "tipo": "Rural",
             "utm_este": 648990.22, "utm_norte": 9402332.96},
            {"centro_poblado": "Almirante Miguel Grau", "poblacion_total": 58, "hombres": 30, "mujeres": 28,
             "poblacion_vulnerable": 21, "viviendas": 32, "tipo": "Rural",
             "utm_este": 649790.07, "utm_norte": 9404060.33},
        ],
    },
    "80": {
        "centros_poblados": ["Yumbe", "Cruz Roja"],
        "comunidades_campesinas": [],
        "poblacion_total": 156, "hombres": 69, "mujeres": 87,
        "poblacion_vulnerable": 22, "viviendas": 52,
        "demografia": [
            {"centro_poblado": "Yumbe", "poblacion_total": 50, "hombres": 25, "mujeres": 25,
             "poblacion_vulnerable": 8, "viviendas": 15, "tipo": "Rural",
             "utm_este": 657882.9, "utm_norte": 9373211.81},
            {"centro_poblado": "Cruz Roja", "poblacion_total": 106, "hombres": 44, "mujeres": 62,
             "poblacion_vulnerable": 14, "viviendas": 37, "tipo": "Rural",
             "utm_este": 656969.55, "utm_norte": 9373412.71},
        ],
    },
    "81": {
        "centros_poblados": ["Hualtacal"],
        "comunidades_campesinas": [],
        "poblacion_total": 80, "hombres": 42, "mujeres": 38,
        "poblacion_vulnerable": 15, "viviendas": 36,
        "demografia": [
            {"centro_poblado": "Hualtacal", "poblacion_total": 80, "hombres": 42, "mujeres": 38,
             "poblacion_vulnerable": 15, "viviendas": 36, "tipo": "Rural",
             "utm_este": 641528.72, "utm_norte": 9401048.22},
        ],
    },
    "82": {
        "centros_poblados": ["Santa Fe de Portachuelo"],
        "comunidades_campesinas": [],
        "poblacion_total": 88, "hombres": 48, "mujeres": 40,
        "poblacion_vulnerable": 24, "viviendas": 45,
        "demografia": [
            {"centro_poblado": "Santa Fe de Portachuelo", "poblacion_total": 88, "hombres": 48, "mujeres": 40,
             "poblacion_vulnerable": 24, "viviendas": 45, "tipo": "Rural",
             "utm_este": 620924.58, "utm_norte": 9444237.76},
        ],
    },
    "83": {
        "centros_poblados": ["Miguel Pampa"],
        "comunidades_campesinas": [],
        "poblacion_total": 188, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Miguel Pampa", "poblacion_total": 188, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
        ],
    },
    "84": {
        "centros_poblados": ["Miguel Pampa"],
        "comunidades_campesinas": [],
        "poblacion_total": 188, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Miguel Pampa", "poblacion_total": 188, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
        ],
    },
    "85": {
        "centros_poblados": ["Dótor"],
        "comunidades_campesinas": [],
        "poblacion_total": 240, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Dótor", "poblacion_total": 240, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
        ],
    },
    "86": {
        "centros_poblados": ["Nueva Esperanza"],
        "comunidades_campesinas": [],
        "poblacion_total": 65, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Nueva Esperanza", "poblacion_total": 65, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
        ],
    },
    "87": {
        "centros_poblados": ["Dótor", "Cardal", "Nueva Esperanza"],
        "comunidades_campesinas": [],
        "poblacion_total": 705, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Dótor", "poblacion_total": 240, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
            {"centro_poblado": "Cardal", "poblacion_total": 400, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
            {"centro_poblado": "Nueva Esperanza", "poblacion_total": 65, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Rural",
             "utm_este": 0.0, "utm_norte": 0.0},
        ],
    },
    "M10B4": {
        "centros_poblados": ["Rio Seco Alto"],
        "comunidades_campesinas": [],
        "poblacion_total": 233, "hombres": 118, "mujeres": 115,
        "poblacion_vulnerable": 54, "viviendas": 113,
        "demografia": [
            {"centro_poblado": "Rio Seco Alto", "poblacion_total": 233, "hombres": 118, "mujeres": 115,
             "poblacion_vulnerable": 54, "viviendas": 113, "tipo": "Rural",
             "utm_este": 596876.16, "utm_norte": 9447574.9},
        ],
    },
    "M11B3": {
        "centros_poblados": ["Quemazon", "La Pareja"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Quemazon", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 641647.19, "utm_norte": 9412507.04},
            {"centro_poblado": "La Pareja", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 639952.07, "utm_norte": 9413029.75},
        ],
    },
    "M12B1": {
        "centros_poblados": ["Nueva Esperanza", "Faicalito"],
        "comunidades_campesinas": [],
        "poblacion_total": 220, "hombres": 108, "mujeres": 112,
        "poblacion_vulnerable": 44, "viviendas": 75,
        "demografia": [
            {"centro_poblado": "Nueva Esperanza", "poblacion_total": 102, "hombres": 49, "mujeres": 53,
             "poblacion_vulnerable": 30, "viviendas": 39, "tipo": "Rural",
             "utm_este": 645366.88, "utm_norte": 9388911.13},
            {"centro_poblado": "Faicalito", "poblacion_total": 118, "hombres": 59, "mujeres": 59,
             "poblacion_vulnerable": 14, "viviendas": 36, "tipo": "Rural",
             "utm_este": 644389.14, "utm_norte": 9390252.82},
        ],
    },
    "M17B1": {
        "centros_poblados": ["Papelillo"],
        "comunidades_campesinas": [],
        "poblacion_total": 367, "hombres": 192, "mujeres": 175,
        "poblacion_vulnerable": 71, "viviendas": 142,
        "demografia": [
            {"centro_poblado": "Papelillo", "poblacion_total": 367, "hombres": 192, "mujeres": 175,
             "poblacion_vulnerable": 71, "viviendas": 142, "tipo": "Rural",
             "utm_este": 599809.73, "utm_norte": 9440145.02},
        ],
    },
    "M17B4": {
        "centros_poblados": ["Chililique Alto"],
        "comunidades_campesinas": [],
        "poblacion_total": 360, "hombres": 176, "mujeres": 184,
        "poblacion_vulnerable": 80, "viviendas": 180,
        "demografia": [
            {"centro_poblado": "Chililique Alto", "poblacion_total": 360, "hombres": 176, "mujeres": 184,
             "poblacion_vulnerable": 80, "viviendas": 180, "tipo": "Rural",
             "utm_este": 605271.82, "utm_norte": 9445305.81},
        ],
    },
    "M17B5": {
        "centros_poblados": ["El Guabo"],
        "comunidades_campesinas": [],
        "poblacion_total": 74, "hombres": 43, "mujeres": 31,
        "poblacion_vulnerable": 11, "viviendas": 20,
        "demografia": [
            {"centro_poblado": "El Guabo", "poblacion_total": 74, "hombres": 43, "mujeres": 31,
             "poblacion_vulnerable": 11, "viviendas": 20, "tipo": "Rural",
             "utm_este": 606700.07, "utm_norte": 9445746.87, "inferido": True},
        ],
    },
    "M17B6": {
        "centros_poblados": ["Platanal Alto", "El Guabo", "Chililique Alto"],
        "comunidades_campesinas": [],
        "poblacion_total": 589, "hombres": 303, "mujeres": 286,
        "poblacion_vulnerable": 127, "viviendas": 265,
        "demografia": [
            {"centro_poblado": "Platanal Alto", "poblacion_total": 155, "hombres": 84, "mujeres": 71,
             "poblacion_vulnerable": 36, "viviendas": 65, "tipo": "Rural",
             "utm_este": 606024.3, "utm_norte": 9446104.76},
            {"centro_poblado": "El Guabo", "poblacion_total": 74, "hombres": 43, "mujeres": 31,
             "poblacion_vulnerable": 11, "viviendas": 20, "tipo": "Rural",
             "utm_este": 606700.07, "utm_norte": 9445746.87},
            {"centro_poblado": "Chililique Alto", "poblacion_total": 360, "hombres": 176, "mujeres": 184,
             "poblacion_vulnerable": 80, "viviendas": 180, "tipo": "Rural",
             "utm_este": 605271.82, "utm_norte": 9445305.81},
        ],
    },
    "M17B7": {
        "centros_poblados": ["Pampa de Ramada"],
        "comunidades_campesinas": [],
        "poblacion_total": 107, "hombres": 51, "mujeres": 56,
        "poblacion_vulnerable": 21, "viviendas": 32,
        "demografia": [
            {"centro_poblado": "Pampa de Ramada", "poblacion_total": 107, "hombres": 51, "mujeres": 56,
             "poblacion_vulnerable": 21, "viviendas": 32, "tipo": "Rural",
             "utm_este": 609224.33, "utm_norte": 9449680.71},
        ],
    },
    "M18B1": {
        "centros_poblados": ["Hualas"],
        "comunidades_campesinas": [],
        "poblacion_total": 63, "hombres": 29, "mujeres": 34,
        "poblacion_vulnerable": 11, "viviendas": 26,
        "demografia": [
            {"centro_poblado": "Hualas", "poblacion_total": 63, "hombres": 29, "mujeres": 34,
             "poblacion_vulnerable": 11, "viviendas": 26, "tipo": "Rural",
             "utm_este": 621408.22, "utm_norte": 9410773.19},
        ],
    },
    "M18B3": {
        "centros_poblados": ["Huaro Quispampa", "Mangomanguia", "Selva Andina"],
        "comunidades_campesinas": [],
        "poblacion_total": 252, "hombres": 140, "mujeres": 112,
        "poblacion_vulnerable": 48, "viviendas": 108,
        "demografia": [
            {"centro_poblado": "Huaro Quispampa", "poblacion_total": 81, "hombres": 42, "mujeres": 39,
             "poblacion_vulnerable": 10, "viviendas": 25, "tipo": "Rural",
             "utm_este": 625484.85, "utm_norte": 9411372.62},
            {"centro_poblado": "Mangomanguia", "poblacion_total": 155, "hombres": 89, "mujeres": 66,
             "poblacion_vulnerable": 37, "viviendas": 74, "tipo": "Rural",
             "utm_este": 626456.1, "utm_norte": 9411525.25},
            {"centro_poblado": "Selva Andina", "poblacion_total": 16, "hombres": 9, "mujeres": 7,
             "poblacion_vulnerable": 1, "viviendas": 9, "tipo": "Rural",
             "utm_este": 624767.98, "utm_norte": 9411446.17},
        ],
    },
    "M18B5": {
        "centros_poblados": ["Morroponcito"],
        "comunidades_campesinas": [],
        "poblacion_total": 75, "hombres": 44, "mujeres": 31,
        "poblacion_vulnerable": 16, "viviendas": 37,
        "demografia": [
            {"centro_poblado": "Morroponcito", "poblacion_total": 75, "hombres": 44, "mujeres": 31,
             "poblacion_vulnerable": 16, "viviendas": 37, "tipo": "Rural",
             "utm_este": 619455.89, "utm_norte": 9412827.69},
        ],
    },
    "M19B2": {
        "centros_poblados": ["Boca Negra"],
        "comunidades_campesinas": [],
        "poblacion_total": 186, "hombres": 99, "mujeres": 87,
        "poblacion_vulnerable": 31, "viviendas": 67,
        "demografia": [
            {"centro_poblado": "Boca Negra", "poblacion_total": 186, "hombres": 99, "mujeres": 87,
             "poblacion_vulnerable": 31, "viviendas": 67, "tipo": "Rural",
             "utm_este": 617148.15, "utm_norte": 9427111.01},
        ],
    },
    "M19B7": {
        "centros_poblados": ["El Faique"],
        "comunidades_campesinas": [],
        "poblacion_total": 40, "hombres": 17, "mujeres": 23,
        "poblacion_vulnerable": 13, "viviendas": 18,
        "demografia": [
            {"centro_poblado": "El Faique", "poblacion_total": 40, "hombres": 17, "mujeres": 23,
             "poblacion_vulnerable": 13, "viviendas": 18, "tipo": "Rural",
             "utm_este": 620081.1, "utm_norte": 9436079.2},
        ],
    },
    "M1B1": {
        "centros_poblados": ["Rio Seco"],
        "comunidades_campesinas": [],
        "poblacion_total": 255, "hombres": 135, "mujeres": 120,
        "poblacion_vulnerable": 60, "viviendas": 106,
        "demografia": [
            {"centro_poblado": "Rio Seco", "poblacion_total": 255, "hombres": 135, "mujeres": 120,
             "poblacion_vulnerable": 60, "viviendas": 106, "tipo": "Rural",
             "utm_este": 618691.27, "utm_norte": 9411039.62},
        ],
    },
    "M20B1": {
        "centros_poblados": ["Las Huacas"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Las Huacas", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 639099.78, "utm_norte": 9399157.03},
        ],
    },
    "M22B1": {
        "centros_poblados": ["Santa Rosa"],
        "comunidades_campesinas": [],
        "poblacion_total": 23, "hombres": 10, "mujeres": 13,
        "poblacion_vulnerable": 2, "viviendas": 9,
        "demografia": [
            {"centro_poblado": "Santa Rosa", "poblacion_total": 23, "hombres": 10, "mujeres": 13,
             "poblacion_vulnerable": 2, "viviendas": 9, "tipo": "Rural",
             "utm_este": 663444.99, "utm_norte": 9404222.74},
        ],
    },
    "M27B1": {
        "centros_poblados": ["Huasimal", "Vicus Linderos", "Vicus la Merced", "Vicus Santa Rosa"],
        "comunidades_campesinas": [],
        "poblacion_total": 459, "hombres": 245, "mujeres": 214,
        "poblacion_vulnerable": 85, "viviendas": 159,
        "demografia": [
            {"centro_poblado": "Huasimal", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 591783.96, "utm_norte": 9430994.91},
            {"centro_poblado": "Vicus Linderos", "poblacion_total": 181, "hombres": 104, "mujeres": 77,
             "poblacion_vulnerable": 33, "viviendas": 66, "tipo": "Rural",
             "utm_este": 593967.02, "utm_norte": 9431291.86},
            {"centro_poblado": "Vicus la Merced", "poblacion_total": 145, "hombres": 75, "mujeres": 70,
             "poblacion_vulnerable": 30, "viviendas": 50, "tipo": "Rural",
             "utm_este": 594302.78, "utm_norte": 9430665.87},
            {"centro_poblado": "Vicus Santa Rosa", "poblacion_total": 133, "hombres": 66, "mujeres": 67,
             "poblacion_vulnerable": 22, "viviendas": 43, "tipo": "Rural",
             "utm_este": 594237.22, "utm_norte": 9428532.75},
        ],
    },
    "M28B2": {
        "centros_poblados": ["Flor de Agua", "Victor Raul (el Checo)"],
        "comunidades_campesinas": [],
        "poblacion_total": 235, "hombres": 119, "mujeres": 116,
        "poblacion_vulnerable": 38, "viviendas": 75,
        "demografia": [
            {"centro_poblado": "Flor de Agua", "poblacion_total": 121, "hombres": 60, "mujeres": 61,
             "poblacion_vulnerable": 16, "viviendas": 36, "tipo": "Rural",
             "utm_este": 636461.8, "utm_norte": 9426124.02},
            {"centro_poblado": "Victor Raul (el Checo)", "poblacion_total": 114, "hombres": 59, "mujeres": 55,
             "poblacion_vulnerable": 22, "viviendas": 39, "tipo": "Rural",
             "utm_este": 635424.03, "utm_norte": 9426188.5},
        ],
    },
    "M28B3": {
        "centros_poblados": ["Ricardo Palma"],
        "comunidades_campesinas": [],
        "poblacion_total": 74, "hombres": 45, "mujeres": 29,
        "poblacion_vulnerable": 11, "viviendas": 20,
        "demografia": [
            {"centro_poblado": "Ricardo Palma", "poblacion_total": 74, "hombres": 45, "mujeres": 29,
             "poblacion_vulnerable": 11, "viviendas": 20, "tipo": "Rural",
             "utm_este": 634159.2, "utm_norte": 9426249.71},
        ],
    },
    "M28B4": {
        "centros_poblados": ["Nueva Esperanza", "Mambluque", "Alto Mambluque"],
        "comunidades_campesinas": [],
        "poblacion_total": 446, "hombres": 228, "mujeres": 218,
        "poblacion_vulnerable": 85, "viviendas": 173,
        "demografia": [
            {"centro_poblado": "Nueva Esperanza", "poblacion_total": 263, "hombres": 130, "mujeres": 133,
             "poblacion_vulnerable": 51, "viviendas": 88, "tipo": "Rural",
             "utm_este": 624543.76, "utm_norte": 9428023.5},
            {"centro_poblado": "Mambluque", "poblacion_total": 121, "hombres": 64, "mujeres": 57,
             "poblacion_vulnerable": 23, "viviendas": 50, "tipo": "Rural",
             "utm_este": 625547.07, "utm_norte": 9426453.6},
            {"centro_poblado": "Alto Mambluque", "poblacion_total": 62, "hombres": 34, "mujeres": 28,
             "poblacion_vulnerable": 11, "viviendas": 35, "tipo": "Rural",
             "utm_este": 626162.28, "utm_norte": 9426053.55},
        ],
    },
    "M2B1": {
        "centros_poblados": ["Santa Rosa"],
        "comunidades_campesinas": [],
        "poblacion_total": 148, "hombres": 71, "mujeres": 77,
        "poblacion_vulnerable": 35, "viviendas": 52,
        "demografia": [
            {"centro_poblado": "Santa Rosa", "poblacion_total": 148, "hombres": 71, "mujeres": 77,
             "poblacion_vulnerable": 35, "viviendas": 52, "tipo": "Rural",
             "utm_este": 636229.38, "utm_norte": 9398524.82},
        ],
    },
    "M2B5": {
        "centros_poblados": ["Hornopampa"],
        "comunidades_campesinas": [],
        "poblacion_total": 261, "hombres": 134, "mujeres": 127,
        "poblacion_vulnerable": 28, "viviendas": 101,
        "demografia": [
            {"centro_poblado": "Hornopampa", "poblacion_total": 261, "hombres": 134, "mujeres": 127,
             "poblacion_vulnerable": 28, "viviendas": 101, "tipo": "Rural",
             "utm_este": 640047.26, "utm_norte": 9394635.3},
        ],
    },
    "M2B8": {
        "centros_poblados": ["Las Huacas", "Huacas Baja"],
        "comunidades_campesinas": [],
        "poblacion_total": 140, "hombres": 66, "mujeres": 74,
        "poblacion_vulnerable": 22, "viviendas": 50,
        "demografia": [
            {"centro_poblado": "Las Huacas", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 639099.78, "utm_norte": 9399157.03},
            {"centro_poblado": "Huacas Baja", "poblacion_total": 140, "hombres": 66, "mujeres": 74,
             "poblacion_vulnerable": 22, "viviendas": 50, "tipo": "Rural",
             "utm_este": 638114.89, "utm_norte": 9398798.85},
        ],
    },
    "M32B3": {
        "centros_poblados": ["Maray"],
        "comunidades_campesinas": [],
        "poblacion_total": 329, "hombres": 165, "mujeres": 164,
        "poblacion_vulnerable": 55, "viviendas": 138,
        "demografia": [
            {"centro_poblado": "Maray", "poblacion_total": 329, "hombres": 165, "mujeres": 164,
             "poblacion_vulnerable": 55, "viviendas": 138, "tipo": "Rural",
             "utm_este": 618786.21, "utm_norte": 9426010.78},
        ],
    },
    "M36B2": {
        "centros_poblados": ["Santa Rosa de Chirimoyos"],
        "comunidades_campesinas": [],
        "poblacion_total": 131, "hombres": 63, "mujeres": 68,
        "poblacion_vulnerable": 29, "viviendas": 53,
        "demografia": [
            {"centro_poblado": "Santa Rosa de Chirimoyos", "poblacion_total": 131, "hombres": 63, "mujeres": 68,
             "poblacion_vulnerable": 29, "viviendas": 53, "tipo": "Rural",
             "utm_este": 625716.5, "utm_norte": 9434887.24},
        ],
    },
    "M3B1": {
        "centros_poblados": ["Piedra Blanca"],
        "comunidades_campesinas": [],
        "poblacion_total": 190, "hombres": 99, "mujeres": 91,
        "poblacion_vulnerable": 33, "viviendas": 96,
        "demografia": [
            {"centro_poblado": "Piedra Blanca", "poblacion_total": 190, "hombres": 99, "mujeres": 91,
             "poblacion_vulnerable": 33, "viviendas": 96, "tipo": "Rural",
             "utm_este": 630950.03, "utm_norte": 9411206.12},
        ],
    },
    "M3B3": {
        "centros_poblados": ["Alan Garcia", "Bigote"],
        "comunidades_campesinas": [],
        "poblacion_total": 146, "hombres": 71, "mujeres": 75,
        "poblacion_vulnerable": 21, "viviendas": 57,
        "demografia": [
            {"centro_poblado": "Alan Garcia", "poblacion_total": 146, "hombres": 71, "mujeres": 75,
             "poblacion_vulnerable": 21, "viviendas": 57, "tipo": "Rural",
             "utm_este": 633196.34, "utm_norte": 9411750.54},
            {"centro_poblado": "Bigote", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 634502.21, "utm_norte": 9411898.39},
        ],
    },
    "M3B5": {
        "centros_poblados": ["San Juan Bautista"],
        "comunidades_campesinas": [],
        "poblacion_total": 116, "hombres": 51, "mujeres": 65,
        "poblacion_vulnerable": 7, "viviendas": 33,
        "demografia": [
            {"centro_poblado": "San Juan Bautista", "poblacion_total": 116, "hombres": 51, "mujeres": 65,
             "poblacion_vulnerable": 7, "viviendas": 33, "tipo": "Rural",
             "utm_este": 635861.76, "utm_norte": 9411993.16},
        ],
    },
    "M3B6": {
        "centros_poblados": ["Manzanares", "Bado de Garzas"],
        "comunidades_campesinas": [],
        "poblacion_total": 202, "hombres": 111, "mujeres": 91,
        "poblacion_vulnerable": 35, "viviendas": 74,
        "demografia": [
            {"centro_poblado": "Manzanares", "poblacion_total": 117, "hombres": 64, "mujeres": 53,
             "poblacion_vulnerable": 21, "viviendas": 38, "tipo": "Rural",
             "utm_este": 637332.87, "utm_norte": 9412499.01},
            {"centro_poblado": "Bado de Garzas", "poblacion_total": 85, "hombres": 47, "mujeres": 38,
             "poblacion_vulnerable": 14, "viviendas": 36, "tipo": "Rural",
             "utm_este": 638051.43, "utm_norte": 9412698.98},
        ],
    },
    "M3B7": {
        "centros_poblados": ["Polluco", "Sinai"],
        "comunidades_campesinas": [],
        "poblacion_total": 68, "hombres": 31, "mujeres": 37,
        "poblacion_vulnerable": 6, "viviendas": 38,
        "demografia": [
            {"centro_poblado": "Polluco", "poblacion_total": 45, "hombres": 19, "mujeres": 26,
             "poblacion_vulnerable": 4, "viviendas": 22, "tipo": "Rural",
             "utm_este": 637525.13, "utm_norte": 9414333.64},
            {"centro_poblado": "Sinai", "poblacion_total": 23, "hombres": 12, "mujeres": 11,
             "poblacion_vulnerable": 2, "viviendas": 16, "tipo": "Rural",
             "utm_este": 639929.96, "utm_norte": 9416155.72},
        ],
    },
    "M3B8": {
        "centros_poblados": ["San Pedro", "Santa Rosa"],
        "comunidades_campesinas": [],
        "poblacion_total": 386, "hombres": 203, "mujeres": 183,
        "poblacion_vulnerable": 43, "viviendas": 139,
        "demografia": [
            {"centro_poblado": "San Pedro", "poblacion_total": 208, "hombres": 112, "mujeres": 96,
             "poblacion_vulnerable": 26, "viviendas": 72, "tipo": "Rural",
             "utm_este": 630638.67, "utm_norte": 9412974.8},
            {"centro_poblado": "Santa Rosa", "poblacion_total": 178, "hombres": 91, "mujeres": 87,
             "poblacion_vulnerable": 17, "viviendas": 67, "tipo": "Rural",
             "utm_este": 632130.33, "utm_norte": 9414106.7},
        ],
    },
    "M3B9": {
        "centros_poblados": ["Tortola"],
        "comunidades_campesinas": [],
        "poblacion_total": 198, "hombres": 99, "mujeres": 99,
        "poblacion_vulnerable": 35, "viviendas": 61,
        "demografia": [
            {"centro_poblado": "Tortola", "poblacion_total": 198, "hombres": 99, "mujeres": 99,
             "poblacion_vulnerable": 35, "viviendas": 61, "tipo": "Rural",
             "utm_este": 628498.15, "utm_norte": 9411522.19},
        ],
    },
    "M4B3": {
        "centros_poblados": ["Chignia Baja"],
        "comunidades_campesinas": [],
        "poblacion_total": 161, "hombres": 81, "mujeres": 80,
        "poblacion_vulnerable": 22, "viviendas": 51,
        "demografia": [
            {"centro_poblado": "Chignia Baja", "poblacion_total": 161, "hombres": 81, "mujeres": 80,
             "poblacion_vulnerable": 22, "viviendas": 51, "tipo": "Rural",
             "utm_este": 643515.18, "utm_norte": 9384081.85},
        ],
    },
    "M4B4": {
        "centros_poblados": ["Hualcas I", "Hualcas Ii"],
        "comunidades_campesinas": [],
        "poblacion_total": 279, "hombres": 145, "mujeres": 134,
        "poblacion_vulnerable": 69, "viviendas": 106,
        "demografia": [
            {"centro_poblado": "Hualcas I", "poblacion_total": 151, "hombres": 77, "mujeres": 74,
             "poblacion_vulnerable": 43, "viviendas": 59, "tipo": "Rural",
             "utm_este": 643289.97, "utm_norte": 9390627.46},
            {"centro_poblado": "Hualcas Ii", "poblacion_total": 128, "hombres": 68, "mujeres": 60,
             "poblacion_vulnerable": 26, "viviendas": 47, "tipo": "Rural",
             "utm_este": 642922.3, "utm_norte": 9389847.83},
        ],
    },
    "M6B10": {
        "centros_poblados": ["La Maravilla", "La Pilca", "Ingenio de Buenos Aires"],
        "comunidades_campesinas": [],
        "poblacion_total": 218, "hombres": 116, "mujeres": 102,
        "poblacion_vulnerable": 39, "viviendas": 76,
        "demografia": [
            {"centro_poblado": "La Maravilla", "poblacion_total": 218, "hombres": 116, "mujeres": 102,
             "poblacion_vulnerable": 39, "viviendas": 76, "tipo": "Rural",
             "utm_este": 617362.1, "utm_norte": 9422166.86},
            {"centro_poblado": "La Pilca", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 616730.87, "utm_norte": 9423183.64},
            {"centro_poblado": "Ingenio de Buenos Aires", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 616796.12, "utm_norte": 9424097.08},
        ],
    },
    "M6B2-2": {
        "centros_poblados": ["Buenos Aires"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Buenos Aires", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 614470.78, "utm_norte": 9417730.18},
        ],
    },
    "M6B2-3": {
        "centros_poblados": ["Pueblo Nuevo", "Pedregal"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "Pueblo Nuevo", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 611697.99, "utm_norte": 9420989.23},
            {"centro_poblado": "Pedregal", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 612343.77, "utm_norte": 9420386.82},
        ],
    },
    "M7B1": {
        "centros_poblados": ["Victor Raul", "Nuevo Progreso", "La Alberca"],
        "comunidades_campesinas": [],
        "poblacion_total": 286, "hombres": 141, "mujeres": 145,
        "poblacion_vulnerable": 39, "viviendas": 121,
        "demografia": [
            {"centro_poblado": "Victor Raul", "poblacion_total": 138, "hombres": 70, "mujeres": 68,
             "poblacion_vulnerable": 18, "viviendas": 49, "tipo": "Rural",
             "utm_este": 627720.39, "utm_norte": 9409361.23},
            {"centro_poblado": "Nuevo Progreso", "poblacion_total": 148, "hombres": 71, "mujeres": 77,
             "poblacion_vulnerable": 21, "viviendas": 72, "tipo": "Rural",
             "utm_este": 628635.92, "utm_norte": 9408671.99},
            {"centro_poblado": "La Alberca", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 630688.04, "utm_norte": 9405337.75},
        ],
    },
    "M7B2": {
        "centros_poblados": ["La Alberca"],
        "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0,
        "demografia": [
            {"centro_poblado": "La Alberca", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 630688.04, "utm_norte": 9405337.75},
        ],
    },
    "M7B3": {
        "centros_poblados": ["Palo Blanco-el Cerezo", "La Tranca"],
        "comunidades_campesinas": [],
        "poblacion_total": 41, "hombres": 25, "mujeres": 16,
        "poblacion_vulnerable": 6, "viviendas": 26,
        "demografia": [
            {"centro_poblado": "Palo Blanco-el Cerezo", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 632853.41, "utm_norte": 9402369.08},
            {"centro_poblado": "La Tranca", "poblacion_total": 41, "hombres": 25, "mujeres": 16,
             "poblacion_vulnerable": 6, "viviendas": 26, "tipo": "Rural",
             "utm_este": 634600.69, "utm_norte": 9400601.21},
        ],
    },
    "M7B6": {
        "centros_poblados": ["Nuevo San Juan", "Santa Rosa", "Serran"],
        "comunidades_campesinas": [],
        "poblacion_total": 235, "hombres": 111, "mujeres": 124,
        "poblacion_vulnerable": 48, "viviendas": 91,
        "demografia": [
            {"centro_poblado": "Nuevo San Juan", "poblacion_total": 87, "hombres": 40, "mujeres": 47,
             "poblacion_vulnerable": 13, "viviendas": 39, "tipo": "Rural",
             "utm_este": 634742.18, "utm_norte": 9400245.46},
            {"centro_poblado": "Santa Rosa", "poblacion_total": 148, "hombres": 71, "mujeres": 77,
             "poblacion_vulnerable": 35, "viviendas": 52, "tipo": "Rural",
             "utm_este": 636229.38, "utm_norte": 9398524.82},
            {"centro_poblado": "Serran", "poblacion_total": 0, "hombres": 0, "mujeres": 0,
             "poblacion_vulnerable": 0, "viviendas": 0, "tipo": "Urbano",
             "utm_este": 635444.95, "utm_norte": 9399322.14},
        ],
    },
    "M8B2": {
        "centros_poblados": ["Botijas"],
        "comunidades_campesinas": [],
        "poblacion_total": 192, "hombres": 100, "mujeres": 92,
        "poblacion_vulnerable": 54, "viviendas": 71,
        "demografia": [
            {"centro_poblado": "Botijas", "poblacion_total": 192, "hombres": 100, "mujeres": 92,
             "poblacion_vulnerable": 54, "viviendas": 71, "tipo": "Rural",
             "utm_este": 615378.57, "utm_norte": 9435504.5},
        ],
    },
    "M9B1": {
        "centros_poblados": ["La Peña"],
        "comunidades_campesinas": [],
        "poblacion_total": 83, "hombres": 45, "mujeres": 38,
        "poblacion_vulnerable": 17, "viviendas": 36,
        "demografia": [
            {"centro_poblado": "La Peña", "poblacion_total": 83, "hombres": 45, "mujeres": 38,
             "poblacion_vulnerable": 17, "viviendas": 36, "tipo": "Rural",
             "utm_este": 593477.33, "utm_norte": 9451361.46},
        ],
    },
}


def datos_bloque(codigo):
    """Entrada del catalogo para un bloque, o una vacia si no figura."""
    return CENTROS_POBLADOS_BLOQUE.get(codigo, {
        "centros_poblados": [], "comunidades_campesinas": [],
        "poblacion_total": 0, "hombres": 0, "mujeres": 0,
        "poblacion_vulnerable": 0, "viviendas": 0, "demografia": [],
    })
