REC = {
 '3': "Infraestructura natural verde: revegetación con nativas y sistemas agroforestales/silvopastoriles. Infraestructura natural marrón: barreras y cercos vivos, zanjas de infiltración y terrazas de formación lenta. Infraestructura complementaria: estabilización puntual de taludes de caminos. Gobernanza: ordenamiento comunitario del pastoreo y control de quemas; evaluar MERESE con Huayabal y Los Checches. Sin propuesta de redelimitación.",
 '6': "Infraestructura natural verde: revegetación nativa y agroforestería/silvopastoril. Infraestructura natural marrón: cercos vivos, zanjas de infiltración y terrazas de formación lenta. Infraestructura complementaria: drenaje y estabilización de la trocha. Gobernanza: gestión de residuos con la municipalidad de Frías; MERESE con Guabal/Huabal. Advierte pendiente máx. 74.5 % próxima al umbral de 75 %. Sin redelimitación.",
 '27': "Técnicamente viable con conservación de suelos compatible con la agricultura, CONDICIONADA a acuerdos previos con titulares prediales. Infraestructura natural verde: revegetación de cárcavas. Infraestructura natural marrón: terrazas de formación lenta, zanjas de infiltración, barreras vivas y diques para control de cárcavas en CAR-01. Infraestructura complementaria: estabilización de CAR-02. Sin redelimitación.",
 '36': "Infraestructura natural verde: revegetación con nativas del Bes-cm y agroforestería/silvopastoril. Infraestructura natural marrón: barreras y cercos vivos, zanjas de infiltración y terrazas de formación lenta. Infraestructura complementaria: drenaje y estabilización puntual de caminos. Gobernanza: ordenamiento comunitario del pastoreo; MERESE con Guabal/Huabal. Sin redelimitación.",
 '39': "Infraestructura natural verde: conservación y enriquecimiento, no restauración intensiva; intervenir la franja de contacto (tercio norte y borde oriental). Evaluar redelimitación por 'límite físico natural': núcleo de conservación estricta sin metas de plantación + franja perimetral activa. Infraestructura complementaria: solo en la calle/trocha de La Cría. Gobernanza: MERESE con usuarios del agua.",
 '56': "Infraestructura natural verde: conservación y enriquecimiento del bosque relicto montano; agroforestería/silvopastoril en la zona agrícola. Infraestructura natural marrón: zanjas de infiltración y terrazas de formación lenta en la zona agrícola. Infraestructura complementaria: estabilización de taludes de la trocha y de laderas sobre viviendas. Gobernanza: SAT comunitario, planes de manejo y MERESE con Putagas y Banda de la Cruz. Salida complementaria o RPAS para el interior.",
 'M17B5': "No aplicar restauración activa uniforme. Infraestructura natural verde: Zona A 8–12 ha restauración activa; Zona B 20–25 ha enriquecimiento; Zona C 38–45 ha conservación estricta. Infraestructura natural marrón: control de erosión en la Zona A y ordenamiento (clausura y rotación) del pastoreo caprino, prioritario. D-05: sectores B y C podrían no calificar como degradados (redelimitación o reclasificación).",
 'M17B6': "Intervención diferenciada. Infraestructura natural verde: restauración activa en la Zona A (10–15 ha); conservación y enriquecimiento con especies CR en las Zonas B y C (90–96 ha). Infraestructura complementaria: estabilización en la Zona A, coordinada con el ejecutor del mejoramiento vial. D-06: evaluar redelimitación o reclasificación de B y C.",
 'M17B7': "Infraestructura natural verde: revegetación y enriquecimiento con nativas del Bes-cm y agroforestería/silvopastoril. Infraestructura natural marrón: cercos vivos, zanjas de infiltración y terrazas de formación lenta. Infraestructura complementaria: estabilización de taludes y drenaje de trocha y badenes. Gobernanza: control de tala y quemas; MERESE con Angurgo. Sin redelimitación.",
 'M17B10': "Evaluar redelimitación por 'límite físico natural': excluir el macizo central con dosel continuo y concentrar la intervención en pie de ladera, borde vial y fondo de valle. Infraestructura natural verde: conservación y enriquecimiento en el sector conservado. Infraestructura complementaria: solo en el corredor vial. Excluir movimiento de tierras en tramos > 50 %.",
}
